version: 2.1

steps:
  - &setup_dependencies
    run:
      name: Install dependencies (required for fabric)
      command: |
        virtualenv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install -r dev-requirements.txt

  - &add_ssh_keys
    add_ssh_keys:
      fingerprints:
        - "44:81:8d:36:86:55:fa:82:eb:97:65:f4:d7:9a:0b:fa"

jobs:
  lint:
      docker:
        - image: circleci/python
      steps:
        - checkout
        - run:
            name: Install lint dependencies and run linting
            command: |
              virtualenv .venv
              source .venv/bin/activate
              pip install flake8==3.5.0
              flake8 --ignore=E501,E722 --exclude=.venv/

  staging:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - *setup_dependencies
      - *add_ssh_keys

      - run:
          name: Backup staging server
          command: |
            source .venv/bin/activate
            fab staging backup

      # TODO: save backup asset somewhere

      - run:
          name: Run migrations and deploy
          command: |
            source .venv/bin/activate
            fab staging migrate

  production:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - *setup_dependencies
      - *add_ssh_keys

      - run:
          name: Backup staging server
          command: |
            source .venv/bin/activate
            fab production backup

      # TODO: save backup asset somewhere

      - run:
          name: Run migrations and deploy
          command: |
            source .venv/bin/activate
            fab production migrate

workflows:
  per_pr:
    jobs:
      - lint
  staging_cd:
    jobs:
      - staging:
          filters:
            branches:
              only: develop
  production_cd:
    jobs:
      - production:
          filters:
            branches:
              only: master
